import Lax235315Proofs.Construction.AdaptiveTapeCounting
import Mathlib.Tactic

/-! A reusable adaptive protocol generated by deterministic state updates.
The next query width may depend on all earlier random blocks. -/

namespace Lax235315Proofs.Construction.AdaptiveStateProtocol

open Lax235315Proofs.Construction.AdaptiveBitBlocks
open Lax235315Proofs.Construction.AdaptiveTapeCounting

variable {State : Type*} (width : State → ℕ)
    (bad : ∀ s, Finset (Tape (width s)))
    (next : ∀ s, Tape (width s) → State)

/-- Run at most `R` random queries starting from a deterministic state. -/
def protocol : (R : ℕ) → State → Protocol R
  | 0, _ => .stop 0
  | R + 1, s => .query (bad s) (fun bits => protocol R (next s bits))

/-- A uniform bound on the bad fraction transfers to every reachable query,
even though its width is selected from the observed earlier blocks. -/
lemma locallyBounded (ε : ℚ)
    (hbad : ∀ s, ((bad s).card : ℚ) ≤ ε * (2 : ℚ) ^ width s) :
    ∀ R s, LocallyBounded ε (protocol width bad next R s) := by
  intro R
  induction R with
  | zero => intro s; trivial
  | succ R ih =>
      intro s
      exact ⟨hbad s, fun bits _ => ih (next s bits)⟩

/-- A state potential paying for the current block and every possible next
state bounds the total number of bits consumed along any adaptive path. -/
lemma maxConsumedBits_le_potential (potential : State → ℕ)
    (hstep : ∀ s bits, width s + potential (next s bits) ≤ potential s) :
    ∀ R s, maxConsumedBits (protocol width bad next R s) ≤ potential s := by
  intro R
  induction R with
  | zero => intro s; simp [protocol, maxConsumedBits]
  | succ R ih =>
      intro s
      simp only [protocol, maxConsumedBits]
      have hsup : (Finset.univ.sup fun bits : Tape (width s) =>
            maxConsumedBits (protocol width bad next R (next s bits))) ≤
          potential s - width s := by
        apply Finset.sup_le
        intro bits _
        have h := ih (next s bits)
        have hs := hstep s bits
        omega
      have hwidth : width s ≤ potential s := by
        let bits : Tape (width s) := fun _ => false
        have := hstep s bits
        omega
      calc
        width s + (Finset.univ.sup fun bits : Tape (width s) =>
            maxConsumedBits (protocol width bad next R (next s bits))) ≤
            width s + (potential s - width s) := Nat.add_le_add_left hsup _
        _ = potential s := by omega

/-- A fixed tape avoids failure at a query exactly when its observed first
block is good and its remaining suffix avoids failure in the selected child. -/
lemma not_mem_failingTapes_query_iff {R k T : ℕ}
    (badBlock : Finset (Tape k)) (child : Tape k → Protocol R)
    (hk : k ≤ T) (hchild : ∀ bits, Fits (child bits) (T - k))
    (tape : Tape T) :
    tape ∉ failingTapes (.query badBlock child) T ⟨hk, hchild⟩ ↔
      let parts := splitEquiv hk tape
      parts.1 ∉ badBlock ∧
        parts.2 ∉ failingTapes (child parts.1) (T - k) (hchild parts.1) := by
  classical
  let parts := splitEquiv hk tape
  have hmem : tape ∈ failingTapes (.query badBlock child) T ⟨hk, hchild⟩ ↔
      parts.1 ∈ badBlock ∨
        parts.2 ∈ failingTapes (child parts.1) (T - k) (hchild parts.1) := by
    constructor
    · intro ht
      simp only [failingTapes, Finset.mem_biUnion, Finset.mem_univ, true_and] at ht
      obtain ⟨bits, hbits⟩ := ht
      obtain ⟨suffix, hsuffix, heq⟩ := Finset.mem_image.mp hbits
      have heqParts : (bits, suffix) = parts := by
        have h := congrArg (splitEquiv hk) heq
        simpa [parts] using h
      have hbitsEq : bits = parts.1 := congrArg Prod.fst heqParts
      have hsuffixEq : suffix = parts.2 := congrArg Prod.snd heqParts
      by_cases hb : bits ∈ badBlock
      · exact Or.inl (hbitsEq ▸ hb)
      · right
        simp only [if_neg hb] at hsuffix
        rw [hbitsEq, hsuffixEq] at hsuffix
        exact hsuffix
    · intro ht
      have hpair : (splitEquiv hk).symm parts = tape := by
        simpa [parts] using (splitEquiv hk).symm_apply_apply tape
      apply Finset.mem_biUnion.mpr
      refine ⟨parts.1, Finset.mem_univ _, ?_⟩
      apply Finset.mem_image.mpr
      refine ⟨parts.2, ?_, by simpa using hpair⟩
      rcases ht with hb | hs
      · simp [hb]
      · by_cases hb : parts.1 ∈ badBlock
        · simp [hb]
        · simpa [hb] using hs
  simp [hmem, parts]

/-- A good path through the decision tree reads only its own sequence of
fresh prefixes, ignoring all tape bits after it stops. -/
def GoodPath : {R : ℕ} → (p : Protocol R) → (T : ℕ) → Fits p T → Tape T → Prop
  | _, .stop _, _, _, _ => True
  | _, .query (k := k) badBlock child, T, hfit, tape => by
      rcases hfit with ⟨hk, hchild⟩
      let parts := splitEquiv hk tape
      exact parts.1 ∉ badBlock ∧
        GoodPath (child parts.1) (T - k) (hchild parts.1) parts.2

/-- The recursive good-path predicate is precisely the complement of the
finite failing-tape set used by the probability count. -/
lemma goodPath_iff_not_mem_failingTapes {R : ℕ} (p : Protocol R)
    (T : ℕ) (hfit : Fits p T) (tape : Tape T) :
    GoodPath p T hfit tape ↔ tape ∉ failingTapes p T hfit := by
  induction p generalizing T with
  | stop r => simp [GoodPath, failingTapes]
  | @query r k badBlock child ih =>
      rcases hfit with ⟨hk, hchild⟩
      rw [not_mem_failingTapes_query_iff badBlock child hk hchild tape]
      dsimp [GoodPath]
      exact and_congr Iff.rfl
        (ih ((splitEquiv hk tape).1) (T - k) (hchild ((splitEquiv hk tape).1))
          ((splitEquiv hk tape).2))

end Lax235315Proofs.Construction.AdaptiveStateProtocol
