import Lax235315Proofs.Construction.AdaptiveTapeCounting
import Mathlib.Tactic

/-! A reusable adaptive protocol generated by deterministic state updates.
The next query width may depend on all earlier random blocks. -/

namespace Lax235315Proofs.Construction.AdaptiveStateProtocol

open Lax235315Proofs.Construction.AdaptiveBitBlocks
open Lax235315Proofs.Construction.AdaptiveTapeCounting

variable {State : Type*} (width : State → ℕ)
    (bad : ∀ s, Finset (Tape (width s)))
    (next : ∀ s, Tape (width s) → State)

/-- Run at most `R` random queries starting from a deterministic state. -/
def protocol : (R : ℕ) → State → Protocol R
  | 0, _ => .stop 0
  | R + 1, s => .query (bad s) (fun bits => protocol R (next s bits))

/-- A uniform bound on the bad fraction transfers to every reachable query,
even though its width is selected from the observed earlier blocks. -/
lemma locallyBounded (ε : ℚ)
    (hbad : ∀ s, ((bad s).card : ℚ) ≤ ε * (2 : ℚ) ^ width s) :
    ∀ R s, LocallyBounded ε (protocol width bad next R s) := by
  intro R
  induction R with
  | zero => intro s; trivial
  | succ R ih =>
      intro s
      exact ⟨hbad s, fun bits _ => ih (next s bits)⟩

/-- A state potential paying for the current block and every possible next
state bounds the total number of bits consumed along any adaptive path. -/
lemma maxConsumedBits_le_potential (potential : State → ℕ)
    (hstep : ∀ s bits, width s + potential (next s bits) ≤ potential s) :
    ∀ R s, maxConsumedBits (protocol width bad next R s) ≤ potential s := by
  intro R
  induction R with
  | zero => intro s; simp [protocol, maxConsumedBits]
  | succ R ih =>
      intro s
      simp only [protocol, maxConsumedBits]
      have hsup : (Finset.univ.sup fun bits : Tape (width s) =>
            maxConsumedBits (protocol width bad next R (next s bits))) ≤
          potential s - width s := by
        apply Finset.sup_le
        intro bits _
        have h := ih (next s bits)
        have hs := hstep s bits
        omega
      have hwidth : width s ≤ potential s := by
        let bits : Tape (width s) := fun _ => false
        have := hstep s bits
        omega
      calc
        width s + (Finset.univ.sup fun bits : Tape (width s) =>
            maxConsumedBits (protocol width bad next R (next s bits))) ≤
            width s + (potential s - width s) := Nat.add_le_add_left hsup _
        _ = potential s := by omega

end Lax235315Proofs.Construction.AdaptiveStateProtocol
